### PR TITLE
fix a bug that cause nvm.sh running multiple times

### PR DESCRIPTION
**Pull request by JesseChan45**
In old version, if you type **npm** then **yarn** for example, the nvm.sh will run twice. Fixed this bug and have some refactor

### CODE REVIEW

**Comment by bchilcott** [comment]
Could you add bun to the list of consumers? I opened #3 for it but might as well just include it here?

**Comment by JesseChan45** [comment]
> Could you add bun to the list of consumers? I opened #3 for it but might as well just include it here?

Of course, bun had been added

**Comment by bchilcott** [comment]
And.. I suppose if we're adding bun then we should include `bunx`? 
https://bun.sh/docs/cli/bunx

**Comment by JesseChan45** [comment]
> And.. I suppose if we're adding bun then we should include `bunx`? https://bun.sh/docs/cli/bunx

Sure

**Comment by undg** [comment]
Thanks guys! Cool refactor.

**Pull request merged**
